import { useEffect, useState } from 'react';
import { KeyboardAvoidingView, Platform, StyleSheet, View } from 'react-native';
import {
  Bubble,
  Day,
  GiftedChat,
  Send,
  SystemMessage,
} from 'react-native-gifted-chat';
import {
  addDoc,
  collection,
  onSnapshot,
  orderBy,
  query,
} from 'firebase/firestore';
import AsyncStorage from '@react-native-async-storage/async-storage';

const Chat = ({ db, navigation, route }) => {
  const [backgroundColor, setBackgroundColor] = useState('#090C08');
  const [messages, setMessages] = useState([]);

  const { name, color, userID } = route.params;

  const backgroundStyle = StyleSheet.create({
    background: {
      flex: 1,
      backgroundColor: backgroundColor,
    },
  });

  // Empty array because we only want to execute code once when the component is mounted
  useEffect(() => {
    // To be executed when mounted/updated
    navigation.setOptions({ title: name });
    setBackgroundColor(color);

    // Getting real-time updates of the database
    // Fetches collection upon mounting, actively listens to changes done to the collection, and will then fetch updated documents
    // collection() has 2 arguments, its first is the database object, second is collection name
    const q = query(collection(db, 'messages'), orderBy('createdAt', 'desc'));
    // onSnapshot takes 2 arguments: 1. reference, 2. callback function that will be called whenever a change has been detected (and once at the start)
    const unsubMessages = onSnapshot(q, (docsSnapshot) => {
      let newMessages = [];

      // For each Firestore doc, we create a new message compatible with Gifted Chat
      // Every object has a document ID `.id`
      // Document properties (like text, time) can be extracted as an object with the .data() function (represeting document's fields and values)
      docsSnapshot.forEach((doc) => {
        newMessages.push({
          // The doc ID is typically not included in the what the data() method retrieves from the Firestoe document
          // Question: Shouldn't it rather be _id: doc.id? or will every message have 2 ids, ths id generated by Firestore, plus the _id generated by gifted chat? is it then even important to pass the Firestore id into the new message? I find the data transfer incredibly hard to follow and understand to be honest...
          id: doc.id,
          ...doc.data(),
          // Date has to be converted, because the way Firestore saves the date is in another format than Gifted Chat needs
          // Question: Won't the new message object have two createdAt objects then? Does it matter?
          createdAt: new Date(doc.data().createdAt.toMillis()),
        });
      });
      setMessages(newMessages);
    });
    // return statement in useEffect will be executed when component is unmounted
    // Cleaning up code, only when unsubMessages is not undefined (to avoid memory leaks)
    // Stops listening to changes
    return () => {
      if (unsubMessages) unsubMessages();
    };
    // Setting static message to be able to see changes in the UI
    // Each message requires ID, creation date and user object as per Gifted Chat library
    // User object requires ID, name, avatar
    // setMessages([
    //   {
    //     _id: 1,
    //     text: 'Hey, what's up?',
    //     createdAt: new Date(),
    //     user: {
    //       _id: 2,
    //       name: 'Fran',
    //       avatar: 'https://picsum.photos/140',
    //     },
    //   },
    //   // Setting system message to indicate chat has been entered
    //   {
    //     _id: 2,
    //     text: 'You entered the chat.',
    //     createdAt: new Date(),
    //     system: true,
    //   },
    // ]);
  }, []);

  // setMessages() is called with callback function, that appends the new message to the previousMessages array, resulting in the newMessages array (set up in a way that multiple messages could be sent at the same time)
  const onSend = (newMessages) => {
    // addDod() automatically adds .id to newly generated document
    // Question: Will the Gifted Chat createdAt property now translated into the Firestore timestamp in this function, hence why it has to be translated back upon fetching?
    addDoc(collection(db, 'messages'), newMessages[0]);
  };

  // Altering speech bubble, inheriting its props but changing wrapperStyle
  const renderBubble = (props) => {
    return (
      <Bubble
        {...props}
        timeTextStyle={{
          right: {
            color: '#FFF',
          },
          left: {
            color: '#F2F2F2',
          },
        }}
        textStyle={{
          right: {
            color: '#FFF',
          },
          left: {
            color: '#F2F2F2',
          },
        }}
        wrapperStyle={{
          right: {
            backgroundColor: '#FF6B6B',
          },
          left: {
            backgroundColor: '#68C3D4',
          },
        }}
      />
    );
  };

  const renderDay = (props) => {
    return (
      <Day
        {...props}
        textStyle={{
          color: '#F2F2F2',
        }}
      />
    );
  };

  const renderSend = (props) => {
    return (
      <Send
        {...props}
        textStyle={{
          color: '#68C3D4',
        }}
      />
    );
  };

  const renderSystemMessage = (props) => {
    return (
      <SystemMessage
        {...props}
        textStyle={{
          color: '#F2F2F2',
        }}
      />
    );
  };

  return (
    <View style={backgroundStyle.background}>
      <GiftedChat
        messages={messages}
        onSend={(messages) => onSend(messages)}
        renderBubble={renderBubble}
        renderDay={renderDay}
        renderSend={renderSend}
        renderSystemMessage={renderSystemMessage}
        sendButtonProps={{ color: 'red' }}
        user={{ _id: userID, name: name }}
      />
      {/* Fix display issue on old Android phones - React Native can check for platform used by user */}
      {Platform.OS === 'android' ? (
        <KeyboardAvoidingView behaviour="height" />
      ) : null}
    </View>
  );
};

export default Chat;
